# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SantaList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                     to='santa.EmailTemplate')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='santa_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='santa.SantaList'),
        ),
    ]
