# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0003_auto_20161120_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='santalist',
            name='secure_hash',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
