# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0006_auto_20161121_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='santalist',
            name='organiser_email',
            field=models.EmailField(max_length=200),
        ),
    ]
